BS/urls.py
from django.urls import path, re_path
from BS import views
from django.contrib.auth import views as auth_views

app_name = 'BS'

urlpatterns = [

	# urls:

	path('', views.index, name='index'),
	path('ar_books/', views.ar_books, name='ar_books'),
	path('en_books/', views.en_books, name='en_books'),
	path('lib_tools/', views.lib_tools, name='lib_tools'),
	path('eng_tools/', views.eng_tools, name='eng_tools'),

]

BookStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	
	path('', include('BS.urls')),
    path('admin/', admin.site.urls),

]

BS/models.py
from django.db import models

# Create your models here.

BS/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
	return render(request, 'BS/index.html')


def ar_books(request):
	return render(request, 'BS/ar_books.html')


def en_books(request):
	return render(request, 'BS/en_books.html')


def lib_tools(request):
	return render(request, 'BS/lib_tools.html')


def eng_tools(request):
	return render(request, 'BS/eng_tools.html')

BS/templates/BS/ar_books.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="rtl" lang="ar" xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store Template, Free CSS Template, TemplateMo.com</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'BS/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
	<div id="templatemo_menu">
        <ul>
            <li><a href="{% url 'BS:index' %}" class="current">الرئيسية</a></li>
        </ul>
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
    </div> <!-- end of header -->
    
    <div id="templatemo_content">
            
        </div> <!-- end of content left -->
        
        <div id="templatemo_content_right">
        	
            <h1>الكتب العربية</span></h1>
            <div class="image_panel"><img src="{% static 'BS/images/newbbg.jpg' %}" alt="CSS Template" width="100" height="150" /></div>
            <p style="color: yellow; font-size: 30px; padding-top: 20px;">اتبع المسار الأصفر من المكتبة</p>
            
             <div class="cleaner_with_height">&nbsp;</div>
                        
        </div> <!-- end of content right -->
    
    	<div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->

<!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
</body>
</html>

BS/templates/BS/en_books.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="rtl" lang="ar" xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'BS/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    <div id="templatemo_menu">
        <ul>
            <li><a href="{% url 'BS:index' %}" class="current">الرئيسية</a></li>
        </ul>
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
    </div> <!-- end of header -->
    
    <div id="templatemo_content">
            
        </div> <!-- end of content left -->
        
        <div id="templatemo_content_right">
        	
            <h1>الكتب الإنجليزية</span></h1>
            <div class="image_panel"><img src="{% static 'BS/images/newbbg.jpg' %}" alt="CSS Template" width="100" height="150" /></div>
            <p style="color: brown; font-size: 30px; padding-top: 20px;">اتبع المسار البني من المكتبة</p>
            
             <div class="cleaner_with_height">&nbsp;</div>
                        
        </div> <!-- end of content right -->
    
    	<div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->

<!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
</body>
</html>

BS/templates/BS/eng_tools.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="rtl" lang="ar" xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'BS/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    <div id="templatemo_menu">
        <ul>
            <li><a href="{% url 'BS:index' %}" class="current">الرئيسية</a></li>
        </ul>
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
    </div> <!-- end of header -->
    
    <div id="templatemo_content">
            
        </div> <!-- end of content left -->
        
        <div id="templatemo_content_right">
        	
            <h1>أدوات هندسية</span></h1>
            <div class="image_panel"><img src="{% static 'BS/images/newbbg.jpg' %}" alt="CSS Template" width="100" height="150" /></div>
            <p style="color: green; font-size: 30px; padding-top: 20px;">اتبع المسار الأخضر من المكتبة</p>
            
             <div class="cleaner_with_height">&nbsp;</div>
                        
        </div> <!-- end of content right -->
    
    	<div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->

<!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
</body>
</html>

BS/templates/BS/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="rtl" lang="ar" xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'BS/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
	<div id="templatemo_menu">
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
    </div> <!-- end of header -->
    
    <div id="templatemo_content">
        
        <div id="templatemo_content_right">

        	<div class="templatemo_product_box">
            	<h1>الكتب العربية</h1>
   	        <img src="{% static 'BS/images/newbbg.jpg' %}" alt="image" />
                <div class="product_info">
                    <div class="buy_now_button"><a href="{% url 'BS:ar_books' %}">الموقع</a></div>
                </div>
                <div class="cleaner">&nbsp;</div>
            </div>
            
            <div class="cleaner_with_width">&nbsp;</div>
            
            <div class="templatemo_product_box">
            	<h1>الكتب الانجليزية</h1>
       	    <img src="{% static 'BS/images/newbbg.jpg' %}" alt="image" />
                <div class="product_info">
                    <div class="buy_now_button"><a href="{% url 'BS:en_books' %}">الموقع</a></div>
                </div>
                <div class="cleaner">&nbsp;</div>
            </div>
            
            <div class="cleaner_with_height">&nbsp;</div>
            
            <div class="templatemo_product_box">
            	<h1>أدوات مكتبية</h1>
   	        <img src="{% static 'BS/images/newbbg.jpg' %}" alt="image" />
                <div class="product_info">
                    <div class="buy_now_button"><a href="{% url 'BS:lib_tools' %}">الموقع</a></div>
                </div>
                <div class="cleaner">&nbsp;</div>
            </div>
            
            <div class="cleaner_with_width">&nbsp;</div>
            
            <div class="templatemo_product_box">
            	<h1>أدوات هندسية</span></h1>
            	<img src="{% static 'BS/images/newbbg.jpg' %}" alt="image" />
                <div class="product_info">
                    <div class="buy_now_button"><a href="{% url 'BS:eng_tools' %}">الموقع</a></div>
                </div>
                <div class="cleaner">&nbsp;</div>
            </div>
            
            <div class="cleaner_with_height">&nbsp;</div>
            
        </div> <!-- end of content right -->
    
    	<div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->
    
    <div id="templatemo_footer">
    
        <!-- Credit: www.templatemo.com -->	</div> 
    <!-- end of footer -->
<!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
</body>
</html>

BS/templates/BS/lib_tools.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="rtl" lang="ar" xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'BS/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    <div id="templatemo_menu">
        <ul>
            <li><a href="{% url 'BS:index' %}" class="current">الرئيسية</a></li>
        </ul>
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
    </div> <!-- end of header -->
    
    <div id="templatemo_content">
            
        </div> <!-- end of content left -->
        
        <div id="templatemo_content_right">
        	
            <h1>القرطاسية</span></h1>
            <div class="image_panel"><img src="{% static 'BS/images/newbbg.jpg' %}" alt="CSS Template" width="100" height="150" /></div>
            <p style="color: pink; font-size: 30px; padding-top: 20px;">اتبع المسار الوردي من المكتبة</p>
            
             <div class="cleaner_with_height">&nbsp;</div>
                        
        </div> <!-- end of content right -->
    
    	<div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->

<!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
</body>
</html>